name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: |
        cd client && npm install
        cd ../server && npm install
        
    - name: Run Tests
      run: |
        cd client && npm test
        cd ../server && npm test
        
    - name: Build Client
      run: cd client && npm run build
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Production
      uses: digitalocean/app-action@main
      with:
        app-name: model-portfolio
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} 